{
  "submission_id": "S91",
  "user_id": "U1",
  "problem_id": "P11",
  "timestamp": "2025-10-09T05:36:59Z",
  "status": "Running... (Testcase 21)",
  "language": "python",
  "test_results": [
    {
      "test_case_number": 1,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 8\n    print(gcd(a, b))\nIndentationError: unexpected indent\nCommand exited with non-zero status 1",
      "execution_time": 0.01,
      "memory_usage": 7.99609375,
      "actual_output": "",
      "expected_output": "2",
      "input": "5698 4838\n"
    },
    {
      "test_case_number": 2,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 8\n    print(gcd(a, b))\nIndentationError: unexpected indent\nCommand exited with non-zero status 1",
      "execution_time": 0.05,
      "memory_usage": 7.90234375,
      "actual_output": "",
      "expected_output": "3",
      "input": "46926 42591\n"
    },
    {
      "test_case_number": 3,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 8\n    print(gcd(a, b))\nIndentationError: unexpected indent\nCommand exited with non-zero status 1",
      "execution_time": 0.01,
      "memory_usage": 7.7734375,
      "actual_output": "",
      "expected_output": "3",
      "input": "1953 192\n"
    },
    {
      "test_case_number": 4,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 8\n    print(gcd(a, b))\nIndentationError: unexpected indent\nCommand exited with non-zero status 1",
      "execution_time": 0.03,
      "memory_usage": 7.5859375,
      "actual_output": "",
      "expected_output": "1",
      "input": "41906 7297\n"
    },
    {
      "test_case_number": 5,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 8\n    print(gcd(a, b))\nIndentationError: unexpected indent\nCommand exited with non-zero status 1",
      "execution_time": 0.0,
      "memory_usage": 7.796875,
      "actual_output": "",
      "expected_output": "1",
      "input": "1 1\n"
    },
    {
      "test_case_number": 6,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 8\n    print(gcd(a, b))\nIndentationError: unexpected indent\nCommand exited with non-zero status 1",
      "execution_time": 0.01,
      "memory_usage": 7.91796875,
      "actual_output": "",
      "expected_output": "2",
      "input": "48266 6718\n"
    },
    {
      "test_case_number": 7,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 8\n    print(gcd(a, b))\nIndentationError: unexpected indent\nCommand exited with non-zero status 1",
      "execution_time": 0.01,
      "memory_usage": 7.765625,
      "actual_output": "",
      "expected_output": "2",
      "input": "36782 13032\n"
    },
    {
      "test_case_number": 8,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 8\n    print(gcd(a, b))\nIndentationError: unexpected indent\nCommand exited with non-zero status 1",
      "execution_time": 0.01,
      "memory_usage": 7.8828125,
      "actual_output": "",
      "expected_output": "50",
      "input": "100 50\n"
    },
    {
      "test_case_number": 9,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 8\n    print(gcd(a, b))\nIndentationError: unexpected indent\nCommand exited with non-zero status 1",
      "execution_time": 0.01,
      "memory_usage": 7.8046875,
      "actual_output": "",
      "expected_output": "25000",
      "input": "50000 25000\n"
    },
    {
      "test_case_number": 10,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 8\n    print(gcd(a, b))\nIndentationError: unexpected indent\nCommand exited with non-zero status 1",
      "execution_time": 0.04,
      "memory_usage": 8.05859375,
      "actual_output": "",
      "expected_output": "3",
      "input": "44349 35742\n"
    },
    {
      "test_case_number": 11,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 8\n    print(gcd(a, b))\nIndentationError: unexpected indent\nCommand exited with non-zero status 1",
      "execution_time": 0.03,
      "memory_usage": 8.11328125,
      "actual_output": "",
      "expected_output": "1",
      "input": "49999 1\n"
    },
    {
      "test_case_number": 12,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 8\n    print(gcd(a, b))\nIndentationError: unexpected indent\nCommand exited with non-zero status 1",
      "execution_time": 0.06,
      "memory_usage": 7.97265625,
      "actual_output": "",
      "expected_output": "1",
      "input": "33119 1740\n"
    },
    {
      "test_case_number": 13,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 8\n    print(gcd(a, b))\nIndentationError: unexpected indent\nCommand exited with non-zero status 1",
      "execution_time": 0.05,
      "memory_usage": 8.10546875,
      "actual_output": "",
      "expected_output": "1",
      "input": "1640 1519\n"
    },
    {
      "test_case_number": 14,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 8\n    print(gcd(a, b))\nIndentationError: unexpected indent\nCommand exited with non-zero status 1",
      "execution_time": 0.01,
      "memory_usage": 7.82421875,
      "actual_output": "",
      "expected_output": "1",
      "input": "4181 2584\n"
    },
    {
      "test_case_number": 15,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 8\n    print(gcd(a, b))\nIndentationError: unexpected indent\nCommand exited with non-zero status 1",
      "execution_time": 0.0,
      "memory_usage": 7.98046875,
      "actual_output": "",
      "expected_output": "1",
      "input": "46368 28657\n"
    },
    {
      "test_case_number": 16,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 8\n    print(gcd(a, b))\nIndentationError: unexpected indent\nCommand exited with non-zero status 1",
      "execution_time": 0.01,
      "memory_usage": 7.8359375,
      "actual_output": "",
      "expected_output": "1",
      "input": "14329 3812\n"
    },
    {
      "test_case_number": 17,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 8\n    print(gcd(a, b))\nIndentationError: unexpected indent\nCommand exited with non-zero status 1",
      "execution_time": 0.01,
      "memory_usage": 7.859375,
      "actual_output": "",
      "expected_output": "3",
      "input": "12345 6789\n"
    },
    {
      "test_case_number": 18,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 8\n    print(gcd(a, b))\nIndentationError: unexpected indent\nCommand exited with non-zero status 1",
      "execution_time": 0.05,
      "memory_usage": 7.86328125,
      "actual_output": "",
      "expected_output": "1",
      "input": "45963 35714\n"
    },
    {
      "test_case_number": 19,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 8\n    print(gcd(a, b))\nIndentationError: unexpected indent\nCommand exited with non-zero status 1",
      "execution_time": 0.01,
      "memory_usage": 8.015625,
      "actual_output": "",
      "expected_output": "50000",
      "input": "50000 50000\n"
    },
    {
      "test_case_number": 20,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 8\n    print(gcd(a, b))\nIndentationError: unexpected indent\nCommand exited with non-zero status 1",
      "execution_time": 0.01,
      "memory_usage": 7.97265625,
      "actual_output": "",
      "expected_output": "1",
      "input": "50000 1\n"
    },
    {
      "test_case_number": 21,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 8\n    print(gcd(a, b))\nIndentationError: unexpected indent\nCommand exited with non-zero status 1",
      "execution_time": 0.01,
      "memory_usage": 7.8203125,
      "actual_output": "",
      "expected_output": "1",
      "input": "9999 9998\n"
    }
  ]
}